backend:
  name: github
  repo: GDK-13/shaggy-solstice
  branch: master

media_folder: "public/media"
public_folder: "media"


collections:
  - name: "projetos"
    label: "Ações e Projetos"
    folder: "src/content/projetos"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      # Trocamos widget "text" por "markdown" para habilitar formatação:
      - {label: "Descrição", name: "description", widget: "markdown"}
      - {label: "Imagem Principal", name: "image", widget: "image", required: false}
      # Nova funcionalidade de Galeria Infinita usando "list":
      - {label: "Galeria de Fotos Extras", name: "gallery", widget: "list", field: {label: "Foto", name: "photo", widget: "image"}, required: false}