backend:
  name: github
  repo: GDK-13/Site-FUNPAPI # Altere para o seu usuário e repo no GitHub
  branch: main # Branch principal do seu repositório

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Página Inicial"
        name: "home"
        file: "src/content/home.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Corpo", name: "body", widget: "markdown"}