backend:
  name: github
  repo: GDK-13/shaggy-solstice # <-- MUDE ISTO PARA O SEU NOME DE UTILIZADOR
  branch: master # ou master, consoante o nome da sua branch

media_folder: "src/app/imports" # Onde as imagens serão guardadas
public_folder: "../imports" # O caminho que o CMS vai usar para mostrar as imagens

collections:
  - name: "projetos"
    label: "Ações e Projetos"
    folder: "src/content/projetos" # Onde os dados dos projetos vão ficar guardados
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Imagem", name: "image", widget: "image"}